import { mulberry32, rngRange, type Rng } from './prng'
import { reflectCircleBoundary, resolveCircleCircle } from './physics'
import type {
  CollisionEffect, Contestant, EliminationEffect, EventType,
  GravityCoreMode, MaterialProfile, Phase, PulseRing,
  SimState, TeamId, TrailPoint
} from './types'
import type { ChallengeRecipeId, RoundPlan, TeamStanding } from './session'

// ─── Constants ────────────────────────────────────────────────────────────────

const TEAMS: TeamId[] = ['GOLD', 'RED', 'CYAN', 'VIOLET', 'EMERALD', 'MAGENTA']
const CONTESTANTS_PER_TEAM = 6
const TOTAL = TEAMS.length * CONTESTANTS_PER_TEAM   // 36

const FULL_BOUNDARY = 460
const CONTESTANT_RADIUS = 16
const CONTESTANT_MASS   = 1
const INIT_SPEED  = 3.5
const MIN_SPEED   = 1.8
const MAX_SPEED   = 8
const WANDER_AMP  = 0.06

const TRAIL_MAX = 12

const EFFECT_POOL_SIZE    = 40
const PULSE_POOL_SIZE     = 6
const COLLISION_POOL_SIZE = 24

const MIN_BOUNDARY = 70

// ─── Phase timing (ticks at 60 TPS) ──────────────────────────────────────────

const T = {
  // Intro (before OPENING)
  INTRO_N:      240, INTRO_T:       60,   // 4s normal / 1s test

  PREPARE_N:    300, PREPARE_T:      60,
  OPENING_N:   3120, OPENING_T:     420,
  DANGER_N:    3120, DANGER_T:      420,
  ESCALATION_N:3600, ESCALATION_T:  600,
  FINAL_N:     2700, FINAL_T:       600,
  WINNER_N:     420, WINNER_T:      120,
  LEADERBOARD_N: 300, LEADERBOARD_T: 120, // 5s normal / 2s test
  RESET_N:      240, RESET_T:        60,
}

// Shorter for SUDDEN_DEATH recipe
const T_SUDDEN = {
  OPENING_N:   1200, OPENING_T:     180,
  DANGER_N:    1200, DANGER_T:      180,
  ESCALATION_N:1800, ESCALATION_T:  300,
  FINAL_N:     1200, FINAL_T:       300,
}

// Shrink rates
const SHRINK_ESCALATION_N = 0.30
const SHRINK_ESCALATION_T = 0.9
const SHRINK_FINAL_N      = 0.65
const SHRINK_FINAL_T      = 2.5
// SUDDEN_DEATH: faster shrink
const SHRINK_ESCALATION_SUDDEN_N = 0.55
const SHRINK_FINAL_SUDDEN_N      = 1.20

// Event intervals
const EVENT_INTERVAL_N = 900
const EVENT_INTERVAL_T = 90

// Danger arc
const DANGER_ARC_SPAN_N  = 0.8
const DANGER_ARC_SPAN_T  = 1.0
const DANGER_ARC_SPEED_N = 0.012
const DANGER_ARC_SPEED_T = 0.04
const DANGER_ARC_DURATION_N = 1800
const DANGER_ARC_DURATION_T = 180

// Gauntlet arc (stronger version for DANGER_ARC_GAUNTLET)
const GAUNTLET_ARC_SPAN_N  = 1.2
const GAUNTLET_ARC_SPEED_N = 0.022
const GAUNTLET_ARC_DURATION_N = 2400

// Repulsor
const REPULSOR_STRENGTH_N = 0.12
const REPULSOR_STRENGTH_T = 0.20
const REPULSOR_DURATION_N = 1800
const REPULSOR_DURATION_T = 150

// Pulse
const PULSE_STRENGTH_N = 2.2
const PULSE_STRENGTH_T = 2.8
const PULSE_DURATION_N = 600
const PULSE_DURATION_T = 90

// Pulse Panic: scheduled pulses
const PULSE_PANIC_INTERVAL_N = 600   // 10s between pulses
const PULSE_PANIC_INTERVAL_T = 90
const PULSE_PANIC_STRENGTH_EARLY_N = 1.6
// Late-phase pulses are generated by addding phaseIdx multiplier inline

// Gravity Core
const GRAVITY_PULL_STRENGTH_N  = 0.09
const GRAVITY_PUSH_STRENGTH_N  = 0.10
const GRAVITY_CORE_DURATION_N  = 1800   // 30s per mode
const GRAVITY_CORE_DURATION_T  = 150

// Milestone
const MILESTONE_DURATION = 180
const TEAM_ELIM_DURATION = 180

// ─── Material profiles ────────────────────────────────────────────────────────

const MATERIAL_CYCLE: MaterialProfile[] = ['POLISHED', 'METALLIC', 'PEARL', 'ENERGY']

function materialForRound(round: number, override: MaterialProfile | null): MaterialProfile {
  if (override !== null) return override
  return MATERIAL_CYCLE[(round - 1) % MATERIAL_CYCLE.length]!
}

// ─── SimConfig ────────────────────────────────────────────────────────────────

export interface SimConfig {
  testMode: boolean
}

// ─── SimEngine ────────────────────────────────────────────────────────────────

export class SimEngine {
  private rng: Rng
  private seed: number
  readonly testMode: boolean
  private pool: Contestant[]
  private effectPool: EliminationEffect[]
  private pulsePool: PulseRing[]
  private collisionPool: CollisionEffect[]

  // Next-event scheduling
  private nextEventTick: number = 0

  // Current recipe id
  private currentRecipeId: ChallengeRecipeId = 'CLASSIC_SURVIVAL'
  // True during championship round
  private isChampionship = false
  private pointMultiplier = 1

  // Gravity core
  private gravityCoreModeTick = 0  // when to switch mode next

  // Pulse Panic scheduling
  private nextPulsePanicTick = 0

  // DANGER_ARC_GAUNTLET: tracks which arc pattern we're on
  private gauntletPattern = 0

  // Last round the leaderboard was shown
  private lastLeaderboardRound = 0

  // Round plans from SessionDNA (optional)
  private roundPlans: RoundPlan[] = []

  // Tournament standings (session-persistent)
  private standings: TeamStanding[] = []

  // Accumulated finish orders for point awarding
  // roundFinishOrder built during WINNER phase
  private finishOrderInProgress: TeamId[] = []

  readonly state: SimState

  // Callback when a round finishes (for tournament director to award points)
  onRoundEnd: ((finishOrder: TeamId[], isChampionship: boolean, multiplier: number) => void) | null = null

  // Allow control panel to override material
  setMaterialOverride(m: MaterialProfile | null): void {
    this.state.materialOverride = m
    this.state.roundMaterial = materialForRound(this.state.round, m)
  }

  // Called by director to inject round plans and standings
  setRoundPlans(plans: RoundPlan[]): void {
    this.roundPlans = plans
  }

  setStandings(standings: TeamStanding[]): void {
    this.standings = standings
    this.syncScoreboardRows()
  }

  // Inject leaderboard display
  showLeaderboard(rows: TeamStanding[]): void {
    const s = this.state
    s.leaderboard.active = true
    s.leaderboard.rows = [...rows]
    s.leaderboard.ticksRemaining = this.t(T.LEADERBOARD_T, T.LEADERBOARD_N)
    s.leaderboard.maxTicks = s.leaderboard.ticksRemaining
    this.lastLeaderboardRound = s.round
  }

  constructor(initialSeed: number, config: SimConfig) {
    this.seed     = initialSeed >>> 0
    this.testMode = config.testMode

    // Pre-allocate contestant pool
    this.pool = []
    for (let i = 0; i < TOTAL; i++) {
      const trail: TrailPoint[] = []
      for (let t = 0; t < TRAIL_MAX; t++) trail.push({ x: 0, y: 0 })
      this.pool.push({
        id: i,
        team: TEAMS[Math.floor(i / CONTESTANTS_PER_TEAM)]!,
        x: 0, y: 0, vx: 0, vy: 0,
        radius: CONTESTANT_RADIUS,
        mass: CONTESTANT_MASS,
        alive: false,
        trail,
        trailHead: 0,
        trailLen: 0,
      })
    }

    // Pre-allocate effect pools
    this.effectPool = []
    for (let i = 0; i < EFFECT_POOL_SIZE; i++) {
      this.effectPool.push({ active: false, x: 0, y: 0, team: 'GOLD', age: 0, maxAge: 0 })
    }
    this.pulsePool = []
    for (let i = 0; i < PULSE_POOL_SIZE; i++) {
      this.pulsePool.push({ active: false, x: 0, y: 0, age: 0, maxAge: 0, color: '#ffffff' })
    }
    this.collisionPool = []
    for (let i = 0; i < COLLISION_POOL_SIZE; i++) {
      this.collisionPool.push({ active: false, x: 0, y: 0, age: 0, maxAge: 0 })
    }

    // Pre-allocate standings
    this.standings = TEAMS.map(team => ({ team, sessionPoints: 0, roundWins: 0 }))

    this.rng = mulberry32(this.seed)
    this.state = {
      tick: 0,
      phase: 'PREPARE',
      round: 0,
      roundTick: 0,
      boundaryRadius:     FULL_BOUNDARY,
      fullBoundaryRadius: FULL_BOUNDARY,
      phaseTicksRemaining: 0,
      contestants: this.pool,
      activeEvent: 'NONE',
      eventTicksRemaining: 0,
      dangerArcAngle: 0,
      dangerArcSpeed: 0,
      dangerArcSpan: 0,
      dangerArcLethal: false,
      repulsorActive: false,
      repulsorStrength: 0,
      pulseRings: this.pulsePool,
      nextPulseCountdown: 0,
      safeSectors: [],
      safeSectorsActive: false,
      pressureActive: false,
      shrinkRate: 0,
      eliminationEffects: this.effectPool,
      collisionEffects: this.collisionPool,
      roundMaterial: 'POLISHED',
      materialOverride: null,
      nextEventLabel: '',
      nextEventTicksRemaining: 0,
      shownFinal10: false,
      shownFinal5: false,
      shownFinalTwo: false,
      milestoneLabel: '',
      milestoneTicksRemaining: 0,
      winnerTeam: null,
      roundDurationSec: 0,
      survivorCount: 0,
      eliminationCount: 0,

      // Pass 2
      currentRecipeId: 'CLASSIC_SURVIVAL',
      currentRecipeName: 'CLASSIC SURVIVAL',
      isChampionshipRound: false,
      sessionPhase: 'EARLY',
      pointMultiplier: 1,

      gravityCoreMode: 'NEUTRAL',
      gravityCoreNextChangeIn: 0,
      gravityCoreStrength: 0,

      teamEliminatedLabel: '',
      teamEliminatedTicksRemaining: 0,

      scoreboardRows: TEAMS.map(team => ({
        team, aliveCount: CONTESTANTS_PER_TEAM, sessionPoints: 0, roundWins: 0, isEliminated: false
      })),

      roundFinishOrder: [],

      roundIntro: {
        active: false,
        recipeName: 'CLASSIC SURVIVAL',
        recipeShortName: 'CLASSIC',
        roundNumber: 1,
        isChampionship: false,
        qualifier: 1,
        positionInQualifier: 1,
        ticksRemaining: 0,
        maxTicks: 0,
      },

      leaderboard: {
        active: false,
        rows: [],
        ticksRemaining: 0,
        maxTicks: 0,
      },

      championshipWin: {
        active: false,
        team: 'GOLD',
        pointsGained: 0,
      },

      currentQualifier: 1,
      currentPositionInQualifier: 0,
    }

    this.beginRound()
  }

  // ─── Helpers ─────────────────────────────────────────────────────────────

  private t<T>(normal: T, test: T): T { return this.testMode ? test : normal }

  // Get plan for current round (0-indexed by round number-1)
  private currentPlan(): RoundPlan | null {
    const idx = this.state.round - 1
    return (idx >= 0 && idx < this.roundPlans.length) ? this.roundPlans[idx]! : null
  }

  private spawnEffect(x: number, y: number, team: TeamId): void {
    for (let i = 0; i < this.effectPool.length; i++) {
      const e = this.effectPool[i]!
      if (!e.active) {
        e.active = true; e.x = x; e.y = y; e.team = team
        e.age = 0; e.maxAge = this.t(22, 18)
        return
      }
    }
    let oldest = this.effectPool[0]!
    for (let i = 1; i < this.effectPool.length; i++) {
      if (this.effectPool[i]!.age > oldest.age) oldest = this.effectPool[i]!
    }
    oldest.active = true; oldest.x = x; oldest.y = y; oldest.team = team
    oldest.age = 0; oldest.maxAge = this.t(22, 18)
  }

  private spawnCollisionEffect(x: number, y: number): void {
    for (let i = 0; i < this.collisionPool.length; i++) {
      const e = this.collisionPool[i]!
      if (!e.active) {
        e.active = true; e.x = x; e.y = y
        e.age = 0; e.maxAge = this.t(14, 10)
        return
      }
    }
    let oldest = this.collisionPool[0]!
    for (let i = 1; i < this.collisionPool.length; i++) {
      if (this.collisionPool[i]!.age > oldest.age) oldest = this.collisionPool[i]!
    }
    oldest.active = true; oldest.x = x; oldest.y = y
    oldest.age = 0; oldest.maxAge = this.t(14, 10)
  }

  private spawnPulseRing(x: number, y: number, color: string): void {
    for (let i = 0; i < this.pulsePool.length; i++) {
      const p = this.pulsePool[i]!
      if (!p.active) {
        p.active = true; p.x = x; p.y = y; p.color = color
        p.age = 0; p.maxAge = this.t(45, 35)
        return
      }
    }
  }

  private syncScoreboardRows(): void {
    // Sync session points/wins from standings into scoreboardRows
    for (const row of this.state.scoreboardRows) {
      const s = this.standings.find(x => x.team === row.team)
      if (s) {
        row.sessionPoints = s.sessionPoints
        row.roundWins = s.roundWins
      }
    }
  }

  // ─── Round lifecycle ──────────────────────────────────────────────────────

  beginRound(): void {
    const s = this.state
    s.round++
    this.seed = (Math.imul(this.seed, 1664525) + 1013904223) >>> 0
    this.rng = mulberry32(this.seed)

    // Determine recipe from plan or fallback to CLASSIC_SURVIVAL
    const plan = this.currentPlan()
    this.currentRecipeId = plan ? plan.recipe.id : 'CLASSIC_SURVIVAL'
    this.isChampionship = plan ? plan.recipe.isChampionship : false
    this.pointMultiplier = plan ? plan.recipe.pointMultiplier : 1

    s.currentRecipeId = this.currentRecipeId
    s.currentRecipeName = plan ? plan.recipe.name : 'CLASSIC SURVIVAL'
    s.isChampionshipRound = this.isChampionship
    s.sessionPhase = plan ? plan.sessionPhase : 'EARLY'
    s.pointMultiplier = this.pointMultiplier
    s.currentQualifier = plan ? plan.qualifier : 1
    s.currentPositionInQualifier = plan ? plan.positionInQualifier : s.round

    // Place contestants
    for (let i = 0; i < TOTAL; i++) {
      const c = this.pool[i]!
      c.alive = true
      const angle = rngRange(this.rng, 0, Math.PI * 2)
      const r     = rngRange(this.rng, 0.15, 0.68) * FULL_BOUNDARY
      c.x = Math.cos(angle) * r
      c.y = Math.sin(angle) * r
      const vAngle = rngRange(this.rng, 0, Math.PI * 2)
      c.vx = Math.cos(vAngle) * INIT_SPEED
      c.vy = Math.sin(vAngle) * INIT_SPEED
      c.trailHead = 0; c.trailLen = 0
    }

    // Reset effect pools
    for (let i = 0; i < this.effectPool.length; i++)    this.effectPool[i]!.active    = false
    for (let i = 0; i < this.pulsePool.length; i++)     this.pulsePool[i]!.active     = false
    for (let i = 0; i < this.collisionPool.length; i++) this.collisionPool[i]!.active = false

    s.tick = 0
    s.roundTick = 0
    s.boundaryRadius     = FULL_BOUNDARY
    s.fullBoundaryRadius = FULL_BOUNDARY
    s.winnerTeam         = null
    s.roundFinishOrder   = []
    this.finishOrderInProgress = []

    s.activeEvent        = 'NONE'
    s.eventTicksRemaining = 0
    s.dangerArcLethal    = false
    s.repulsorActive     = false
    s.repulsorStrength   = 0
    s.safeSectors        = []
    s.safeSectorsActive  = false
    s.pressureActive     = false
    s.shrinkRate         = 0
    s.nextPulseCountdown = 0

    s.gravityCoreMode       = 'NEUTRAL'
    s.gravityCoreNextChangeIn = 0
    s.gravityCoreStrength   = 0
    this.gravityCoreModeTick = 0
    this.gauntletPattern    = 0
    this.nextPulsePanicTick = 0

    s.roundMaterial = plan
      ? plan.materialProfile
      : materialForRound(s.round, s.materialOverride)
    // Respect manual override
    if (s.materialOverride !== null) s.roundMaterial = s.materialOverride

    s.shownFinal10 = false
    s.shownFinal5  = false
    s.shownFinalTwo = false
    s.milestoneLabel = ''
    s.milestoneTicksRemaining = 0
    s.teamEliminatedLabel = ''
    s.teamEliminatedTicksRemaining = 0

    s.roundDurationSec = 0
    s.survivorCount = 0
    s.eliminationCount = 0

    // Reset scoreboard alive counts
    for (const row of s.scoreboardRows) {
      row.aliveCount = CONTESTANTS_PER_TEAM
      row.isEliminated = false
    }
    this.syncScoreboardRows()

    s.championshipWin.active = false

    // Schedule first event
    this.nextEventTick = 0

    // Show intro
    s.roundIntro = {
      active: true,
      recipeName: s.currentRecipeName,
      recipeShortName: plan ? plan.recipe.shortName : 'CLASSIC',
      roundNumber: s.round,
      isChampionship: this.isChampionship,
      qualifier: s.currentQualifier,
      positionInQualifier: s.currentPositionInQualifier,
      ticksRemaining: this.t(T.INTRO_T, T.INTRO_N),
      maxTicks: this.t(T.INTRO_T, T.INTRO_N),
    }
    s.phase = 'INTRO'
    s.phaseTicksRemaining = s.roundIntro.ticksRemaining

    this.updateNextEventHint()
  }

  private updateNextEventHint(): void {
    const recipe = this.currentRecipeId
    // PULSE_PANIC: uses nextPulseCountdown instead
    if (recipe === 'PULSE_PANIC') {
      if (this.nextPulsePanicTick > 0) {
        const ticks = this.nextPulsePanicTick - this.state.roundTick
        this.state.nextPulseCountdown = Math.max(0, ticks)
      }
      this.state.nextEventLabel = ''
      this.state.nextEventTicksRemaining = 0
      return
    }

    const ticks = this.nextEventTick - this.state.roundTick
    if (ticks <= 0 || this.state.activeEvent !== 'NONE') {
      this.state.nextEventLabel = ''
      this.state.nextEventTicksRemaining = 0
      return
    }
    const sec = Math.ceil(ticks / 60)
    const labels = ['DANGER ARC IN', 'REPULSOR IN', 'PULSE IN', 'EVENT IN']
    const li = Math.floor(this.state.round % labels.length)
    this.state.nextEventLabel = (labels[li] ?? 'EVENT IN') + ' ' + sec
    this.state.nextEventTicksRemaining = ticks
  }

  // ─── Main step ───────────────────────────────────────────────────────────

  step(): void {
    this.state.tick++
    this.state.roundTick++
    this.state.phaseTicksRemaining--

    this.ageEffects()

    const phase = this.state.phase

    if (phase === 'INTRO') {
      // Contestants placed but immobile during intro — just age
      if (this.state.phaseTicksRemaining <= 0) {
        this.state.roundIntro.active = false
        this.enterPhase('PREPARE')
      }
      return
    }

    if (phase === 'LEADERBOARD') {
      if (this.state.leaderboard.ticksRemaining > 0) {
        this.state.leaderboard.ticksRemaining--
      }
      if (this.state.phaseTicksRemaining <= 0) {
        this.state.leaderboard.active = false
        this.state.phase = 'RESET'
        this.state.phaseTicksRemaining = this.t(T.RESET_T, T.RESET_N)
      }
      return
    }

    if (phase === 'PREPARE') {
      this.integrate()
      this.collide(false)
      if (this.state.phaseTicksRemaining <= 0) {
        this.enterPhase('OPENING')
      }

    } else if (phase === 'OPENING') {
      // GRAVITY_CORE: activate core from opening
      if (this.currentRecipeId === 'GRAVITY_CORE') {
        this.tickGravityCore()
      }
      this.integrate()
      this.collide(false)
      this.checkMilestones()
      if (this.state.phaseTicksRemaining <= 0) {
        this.enterPhase('DANGER')
      }

    } else if (phase === 'DANGER') {
      this.tickEvent()
      if (this.currentRecipeId === 'GRAVITY_CORE') this.tickGravityCore()
      this.integrate()
      this.applyRepulsor()
      this.applyDangerArc()
      this.applyGravityCore()
      this.collide(false)
      this.checkMilestones()
      this.checkTeamEliminations()
      if (this.state.phaseTicksRemaining <= 0) {
        this.endEvent()
        this.enterPhase('ESCALATION')
      }

    } else if (phase === 'ESCALATION') {
      this.tickEvent()
      if (this.currentRecipeId === 'GRAVITY_CORE') this.tickGravityCore()
      // Shrink
      this.state.pressureActive = true
      const isSudden = this.currentRecipeId === 'SUDDEN_DEATH'
      this.state.shrinkRate = this.t(SHRINK_ESCALATION_T,
        isSudden ? SHRINK_ESCALATION_SUDDEN_N : SHRINK_ESCALATION_N)
      this.state.boundaryRadius = Math.max(
        MIN_BOUNDARY + 80,
        this.state.boundaryRadius - this.state.shrinkRate
      )
      this.integrate()
      this.applyRepulsor()
      this.applyDangerArc()
      this.applyGravityCore()
      this.eliminateOutside()
      this.collide(true)
      this.checkMilestones()
      this.checkTeamEliminations()

      const winner = this.findWinner()
      if (winner !== null) {
        this.triggerWinner(winner)
      } else if (this.state.phaseTicksRemaining <= 0) {
        this.endEvent()
        this.enterPhase('FINAL')
      }

    } else if (phase === 'FINAL') {
      this.tickEvent()
      if (this.currentRecipeId === 'GRAVITY_CORE') this.tickGravityCore()
      const isSudden = this.currentRecipeId === 'SUDDEN_DEATH'
      this.state.shrinkRate = this.t(SHRINK_FINAL_T,
        isSudden ? SHRINK_FINAL_SUDDEN_N : SHRINK_FINAL_N)
      this.state.boundaryRadius = Math.max(
        MIN_BOUNDARY,
        this.state.boundaryRadius - this.state.shrinkRate
      )
      this.integrate()
      this.applyRepulsor()
      this.applyDangerArc()
      this.applyGravityCore()
      this.eliminateOutside()
      this.collide(true)
      this.checkMilestones()
      this.checkTeamEliminations()

      const winner = this.findWinner()
      if (winner !== null) {
        this.triggerWinner(winner)
      } else if (
        this.state.boundaryRadius <= MIN_BOUNDARY ||
        this.state.phaseTicksRemaining <= 0
      ) {
        this.triggerWinner(this.majorityTeam())
      }

    } else if (phase === 'WINNER') {
      this.integrateWinner()
      if (this.state.phaseTicksRemaining <= 0) {
        // Fire round end callback
        if (this.onRoundEnd && this.state.winnerTeam !== null) {
          this.onRoundEnd(this.finishOrderInProgress, this.isChampionship, this.pointMultiplier)
        }
        // Decide if leaderboard should show
        const roundsSinceLB = this.state.round - this.lastLeaderboardRound
        const showLB = roundsSinceLB >= 5
        if (showLB) {
          this.state.phase = 'LEADERBOARD'
          this.state.phaseTicksRemaining = this.t(T.LEADERBOARD_T, T.LEADERBOARD_N)
          this.state.leaderboard.active = true
          this.state.leaderboard.ticksRemaining = this.state.phaseTicksRemaining
          this.state.leaderboard.maxTicks = this.state.phaseTicksRemaining
          this.lastLeaderboardRound = this.state.round
        } else {
          this.state.phase = 'RESET'
          this.state.phaseTicksRemaining = this.t(T.RESET_T, T.RESET_N)
        }
      }

    } else if (phase === 'RESET') {
      if (this.state.phaseTicksRemaining <= 0) {
        this.beginRound()
      }
    }

    // Milestone decay
    if (this.state.milestoneTicksRemaining > 0) {
      this.state.milestoneTicksRemaining--
    } else {
      this.state.milestoneLabel = ''
    }

    // Team eliminated label decay
    if (this.state.teamEliminatedTicksRemaining > 0) {
      this.state.teamEliminatedTicksRemaining--
    } else {
      this.state.teamEliminatedLabel = ''
    }
  }

  // ─── Phase entry ─────────────────────────────────────────────────────────

  private enterPhase(phase: Phase): void {
    this.state.phase = phase
    const recipe = this.currentRecipeId

    switch (phase) {
      case 'PREPARE':
        this.state.phaseTicksRemaining = this.t(T.PREPARE_T, T.PREPARE_N)
        break

      case 'OPENING': {
        let opDur: number
        if (recipe === 'SUDDEN_DEATH') {
          opDur = this.t(T_SUDDEN.OPENING_T, T_SUDDEN.OPENING_N)
        } else {
          opDur = this.t(T.OPENING_T, T.OPENING_N)
        }
        this.state.phaseTicksRemaining = opDur
        this.nextEventTick = this.state.roundTick + opDur + this.t(EVENT_INTERVAL_T, EVENT_INTERVAL_N) / 2
        // PULSE_PANIC: schedule first pulse from OPENING
        if (recipe === 'PULSE_PANIC') {
          this.nextPulsePanicTick = this.state.roundTick + this.t(PULSE_PANIC_INTERVAL_T, PULSE_PANIC_INTERVAL_N)
        }
        // GRAVITY_CORE: set initial mode
        if (recipe === 'GRAVITY_CORE') {
          this.setNextGravityCoreMode()
        }
        break
      }

      case 'DANGER': {
        let dDur: number
        if (recipe === 'SUDDEN_DEATH') {
          dDur = this.t(T_SUDDEN.DANGER_T, T_SUDDEN.DANGER_N)
        } else {
          dDur = this.t(T.DANGER_T, T.DANGER_N)
        }
        this.state.phaseTicksRemaining = dDur
        this.nextEventTick = this.state.roundTick + this.t(60, 300)
        // GAUNTLET: fire first arc immediately in DANGER
        if (recipe === 'DANGER_ARC_GAUNTLET') {
          this.nextEventTick = this.state.roundTick + this.t(30, 120)
        }
        // PULSE_PANIC: schedule from DANGER
        if (recipe === 'PULSE_PANIC') {
          this.nextPulsePanicTick = this.state.roundTick + this.t(PULSE_PANIC_INTERVAL_T / 2, PULSE_PANIC_INTERVAL_N / 2)
        }
        break
      }

      case 'ESCALATION': {
        let eDur: number
        if (recipe === 'SUDDEN_DEATH') {
          eDur = this.t(T_SUDDEN.ESCALATION_T, T_SUDDEN.ESCALATION_N)
        } else {
          eDur = this.t(T.ESCALATION_T, T.ESCALATION_N)
        }
        this.state.phaseTicksRemaining = eDur
        this.nextEventTick = this.state.roundTick + this.t(45, 240)
        break
      }

      case 'FINAL': {
        let fDur: number
        if (recipe === 'SUDDEN_DEATH') {
          fDur = this.t(T_SUDDEN.FINAL_T, T_SUDDEN.FINAL_N)
        } else {
          fDur = this.t(T.FINAL_T, T.FINAL_N)
        }
        this.state.phaseTicksRemaining = fDur
        this.nextEventTick = this.state.roundTick + this.t(30, 180)
        break
      }

      default:
        break
    }
    this.updateNextEventHint()
  }

  // ─── Event system ────────────────────────────────────────────────────────

  private tickEvent(): void {
    const rt = this.state.roundTick
    const phase = this.state.phase
    const recipe = this.currentRecipeId

    // PULSE_PANIC: scheduled pulses take priority
    if (recipe === 'PULSE_PANIC') {
      this.tickPulsePanic(phase)
      return
    }

    // Advance danger arc
    if (this.state.activeEvent === 'DANGER_ARC') {
      this.state.dangerArcAngle += this.state.dangerArcSpeed
      this.state.eventTicksRemaining--
      if (this.state.eventTicksRemaining <= 0) {
        this.endEvent()
        // GAUNTLET: immediately schedule next arc
        if (recipe === 'DANGER_ARC_GAUNTLET') {
          this.gauntletPattern++
          this.nextEventTick = rt + this.t(30, 90)
        }
      } else {
        const duration = recipe === 'DANGER_ARC_GAUNTLET'
          ? this.t(DANGER_ARC_DURATION_T, GAUNTLET_ARC_DURATION_N)
          : this.t(DANGER_ARC_DURATION_T, DANGER_ARC_DURATION_N)
        this.state.dangerArcLethal = this.state.eventTicksRemaining < (duration - 20)
      }
      this.updateNextEventHint()
      return
    }

    if (this.state.activeEvent === 'CENTER_REPULSOR') {
      this.state.eventTicksRemaining--
      if (this.state.eventTicksRemaining <= 0) this.endEvent()
      this.updateNextEventHint()
      return
    }

    if (this.state.activeEvent === 'PULSE') {
      this.state.eventTicksRemaining--
      if (this.state.eventTicksRemaining <= 0) this.endEvent()
      this.updateNextEventHint()
      return
    }

    // Fire next event
    if (
      (phase === 'DANGER' || phase === 'ESCALATION' || phase === 'FINAL') &&
      this.state.activeEvent === 'NONE' &&
      rt >= this.nextEventTick
    ) {
      this.fireNextEvent()
    }
    this.updateNextEventHint()
  }

  private tickPulsePanic(phase: string): void {
    if (phase !== 'DANGER' && phase !== 'ESCALATION' && phase !== 'FINAL') return
    const rt = this.state.roundTick

    // Update countdown display
    const countdown = this.nextPulsePanicTick - rt
    this.state.nextPulseCountdown = Math.max(0, countdown)

    if (rt >= this.nextPulsePanicTick && this.nextPulsePanicTick > 0) {
      // Determine pulse strength: increases over time
      const phaseIdx = phase === 'DANGER' ? 0 : phase === 'ESCALATION' ? 1 : 2
      const strength = this.t(
        PULSE_PANIC_STRENGTH_EARLY_N + (phaseIdx * 0.5) + (this.rng() * 0.4),
        PULSE_STRENGTH_T
      )
      this.firePulseWithStrength(strength)
      // Schedule next: interval gets shorter each phase
      const interval = this.t(
        Math.max(60, PULSE_PANIC_INTERVAL_T - phaseIdx * 15),
        Math.max(540, PULSE_PANIC_INTERVAL_N - phaseIdx * 120)
      )
      this.nextPulsePanicTick = rt + interval + Math.floor(this.rng() * (interval * 0.3))
    }
  }

  private fireNextEvent(): void {
    const recipe = this.currentRecipeId

    let chosen: EventType

    if (recipe === 'DANGER_ARC_GAUNTLET') {
      // Always fire danger arc
      chosen = 'DANGER_ARC'
    } else if (recipe === 'CLASSIC_SURVIVAL' || recipe === 'LAST_COLOR_STANDING') {
      const pick = Math.floor(this.rng() * 3)
      const events: EventType[] = ['DANGER_ARC', 'CENTER_REPULSOR', 'PULSE']
      chosen = events[pick % events.length] ?? 'PULSE'
    } else if (recipe === 'SUDDEN_DEATH') {
      // Faster danger arc only
      chosen = 'DANGER_ARC'
    } else {
      const pick = Math.floor(this.rng() * 3)
      const events: EventType[] = ['DANGER_ARC', 'CENTER_REPULSOR', 'PULSE']
      chosen = events[pick % events.length] ?? 'PULSE'
    }

    this.state.activeEvent = chosen

    switch (chosen) {
      case 'DANGER_ARC': {
        const isGauntlet = recipe === 'DANGER_ARC_GAUNTLET'
        const isSudden   = recipe === 'SUDDEN_DEATH'
        this.state.dangerArcAngle = rngRange(this.rng, 0, Math.PI * 2)
        // Gauntlet: add second arc offset by PI
        const speedMult = isGauntlet ? 1.8 : isSudden ? 1.5 : 1.0
        this.state.dangerArcSpeed = rngRange(this.rng, 0.5, 1.5) *
          (this.rng() > 0.5 ? 1 : -1) *
          this.t(DANGER_ARC_SPEED_T, isGauntlet ? GAUNTLET_ARC_SPEED_N : DANGER_ARC_SPEED_N) * speedMult
        this.state.dangerArcSpan  = this.t(DANGER_ARC_SPAN_T, isGauntlet ? GAUNTLET_ARC_SPAN_N : DANGER_ARC_SPAN_N)
        this.state.dangerArcLethal = false
        this.state.eventTicksRemaining = this.t(DANGER_ARC_DURATION_T,
          isGauntlet ? GAUNTLET_ARC_DURATION_N : DANGER_ARC_DURATION_N)
        break
      }
      case 'CENTER_REPULSOR':
        this.state.repulsorActive   = true
        this.state.repulsorStrength = this.t(REPULSOR_STRENGTH_T, REPULSOR_STRENGTH_N)
        this.state.eventTicksRemaining = this.t(REPULSOR_DURATION_T, REPULSOR_DURATION_N)
        break
      case 'PULSE':
        this.firePulseWithStrength(this.t(PULSE_STRENGTH_T, PULSE_STRENGTH_N))
        this.state.eventTicksRemaining = this.t(PULSE_DURATION_T, PULSE_DURATION_N)
        break
    }

    // Schedule next event
    const recipe2 = this.currentRecipeId
    const interval = recipe2 === 'DANGER_ARC_GAUNTLET'
      ? this.t(30, 600)     // gauntlet: tight sequence
      : recipe2 === 'SUDDEN_DEATH'
      ? this.t(45, 450)     // sudden death: faster
      : this.t(EVENT_INTERVAL_T, EVENT_INTERVAL_N)
    this.nextEventTick = this.state.roundTick + interval
  }

  private firePulseWithStrength(strength: number): void {
    for (let i = 0; i < TOTAL; i++) {
      const c = this.pool[i]!
      if (!c.alive) continue
      const d = Math.sqrt(c.x * c.x + c.y * c.y)
      if (d < 1) continue
      const nx = c.x / d
      const ny = c.y / d
      const imp = strength * Math.max(0.3, 1 - d / FULL_BOUNDARY)
      c.vx += nx * imp
      c.vy += ny * imp
      const spd = Math.sqrt(c.vx * c.vx + c.vy * c.vy)
      if (spd > MAX_SPEED) { c.vx *= MAX_SPEED / spd; c.vy *= MAX_SPEED / spd }
    }
    this.spawnPulseRing(0, 0, '#00ddff')
  }

  private endEvent(): void {
    this.state.activeEvent       = 'NONE'
    this.state.eventTicksRemaining = 0
    this.state.dangerArcLethal   = false
    this.state.repulsorActive    = false
    this.state.repulsorStrength  = 0
  }

  // ─── Gravity Core ─────────────────────────────────────────────────────────

  private setNextGravityCoreMode(): void {
    const modes: GravityCoreMode[] = ['PULL', 'PUSH', 'NEUTRAL', 'PULL', 'PUSH']
    const pick = Math.floor(this.rng() * modes.length)
    this.state.gravityCoreMode = modes[pick] ?? 'NEUTRAL'
    const dur = this.t(GRAVITY_CORE_DURATION_T, GRAVITY_CORE_DURATION_N)
    this.gravityCoreModeTick = this.state.roundTick + dur
    this.state.gravityCoreNextChangeIn = dur
    const mode = this.state.gravityCoreMode
    this.state.gravityCoreStrength = mode === 'NEUTRAL' ? 0
      : mode === 'PULL' ? GRAVITY_PULL_STRENGTH_N
      : GRAVITY_PUSH_STRENGTH_N
  }

  private tickGravityCore(): void {
    const rt = this.state.roundTick
    this.state.gravityCoreNextChangeIn = Math.max(0, this.gravityCoreModeTick - rt)
    if (rt >= this.gravityCoreModeTick && this.gravityCoreModeTick > 0) {
      this.setNextGravityCoreMode()
    }
  }

  private applyGravityCore(): void {
    if (this.currentRecipeId !== 'GRAVITY_CORE') return
    const mode = this.state.gravityCoreMode
    if (mode === 'NEUTRAL') return

    const str = this.state.gravityCoreStrength
    const sign = mode === 'PULL' ? -1 : 1   // PULL: toward center (negative radial)

    for (let i = 0; i < TOTAL; i++) {
      const c = this.pool[i]!
      if (!c.alive) continue
      const d = Math.sqrt(c.x * c.x + c.y * c.y)
      if (d < 1) continue
      const nx = c.x / d
      const ny = c.y / d
      c.vx += sign * nx * str
      c.vy += sign * ny * str
      const spd = Math.sqrt(c.vx * c.vx + c.vy * c.vy)
      if (spd > MAX_SPEED) { c.vx *= MAX_SPEED / spd; c.vy *= MAX_SPEED / spd }
    }
  }

  // ─── Physics helpers ─────────────────────────────────────────────────────

  private integrate(): void {
    for (let i = 0; i < TOTAL; i++) {
      const c = this.pool[i]!
      if (!c.alive) continue

      c.trail[c.trailHead]!.x = c.x
      c.trail[c.trailHead]!.y = c.y
      c.trailHead = (c.trailHead + 1) % TRAIL_MAX
      if (c.trailLen < TRAIL_MAX) c.trailLen++

      const speed = Math.sqrt(c.vx * c.vx + c.vy * c.vy)
      const curAngle = Math.atan2(c.vy, c.vx)
      const newAngle = curAngle + rngRange(this.rng, -WANDER_AMP, WANDER_AMP)
      const s = speed < MIN_SPEED ? MIN_SPEED : speed
      c.vx = Math.cos(newAngle) * s
      c.vy = Math.sin(newAngle) * s

      c.x += c.vx
      c.y += c.vy
    }
  }

  private integrateWinner(): void {
    for (let i = 0; i < TOTAL; i++) {
      const c = this.pool[i]!
      if (!c.alive) continue
      c.vx *= 0.96
      c.vy *= 0.96
      c.x += c.vx
      c.y += c.vy
      reflectCircleBoundary(c, this.state.boundaryRadius)
    }
  }

  private applyRepulsor(): void {
    if (!this.state.repulsorActive) return
    const str = this.state.repulsorStrength
    for (let i = 0; i < TOTAL; i++) {
      const c = this.pool[i]!
      if (!c.alive) continue
      const d = Math.sqrt(c.x * c.x + c.y * c.y)
      if (d < 1) continue
      const nx = c.x / d
      const ny = c.y / d
      const factor = Math.max(0, 1 - d / FULL_BOUNDARY) * str
      c.vx += nx * factor
      c.vy += ny * factor
      const spd = Math.sqrt(c.vx * c.vx + c.vy * c.vy)
      if (spd > MAX_SPEED) { c.vx *= MAX_SPEED / spd; c.vy *= MAX_SPEED / spd }
    }
  }

  private applyDangerArc(): void {
    if (!this.state.dangerArcLethal) return
    if (this.state.activeEvent !== 'DANGER_ARC') return

    const boundary = this.state.boundaryRadius
    const arcAngle = this.state.dangerArcAngle
    const halfSpan = this.state.dangerArcSpan

    for (let i = 0; i < TOTAL; i++) {
      const c = this.pool[i]!
      if (!c.alive) continue
      const d = Math.sqrt(c.x * c.x + c.y * c.y)
      if (d < boundary - c.radius * 3) continue
      const angle = Math.atan2(c.y, c.x)
      const diff = angleDiff(angle, arcAngle)
      if (Math.abs(diff) < halfSpan) {
        c.alive = false
        this.spawnEffect(c.x, c.y, c.team)
        this.state.eliminationCount++
      }
    }

    // GAUNTLET: second arc at opposite side
    if (this.currentRecipeId === 'DANGER_ARC_GAUNTLET' && this.gauntletPattern % 2 === 1) {
      const arcAngle2 = arcAngle + Math.PI
      for (let i = 0; i < TOTAL; i++) {
        const c = this.pool[i]!
        if (!c.alive) continue
        const d = Math.sqrt(c.x * c.x + c.y * c.y)
        if (d < boundary - c.radius * 3) continue
        const angle = Math.atan2(c.y, c.x)
        const diff = angleDiff(angle, arcAngle2)
        if (Math.abs(diff) < halfSpan) {
          c.alive = false
          this.spawnEffect(c.x, c.y, c.team)
          this.state.eliminationCount++
        }
      }
    }
  }

  private collide(escalation: boolean): void {
    const boundary = this.state.boundaryRadius
    if (!escalation) {
      for (let i = 0; i < TOTAL; i++) {
        if (this.pool[i]!.alive) reflectCircleBoundary(this.pool[i]!, boundary)
      }
    }

    const COLLISION_THRESHOLD = 2.5

    for (let i = 0; i < TOTAL - 1; i++) {
      if (!this.pool[i]!.alive) continue
      for (let j = i + 1; j < TOTAL; j++) {
        if (!this.pool[j]!.alive) continue
        const a = this.pool[i]!
        const b = this.pool[j]!

        const dx = b.x - a.x
        const dy = b.y - a.y
        const distSq = dx * dx + dy * dy
        const minDist = a.radius + b.radius
        if (distSq < minDist * minDist && distSq > 0) {
          const dist = Math.sqrt(distSq)
          const nx = dx / dist
          const ny = dy / dist
          const relVDotN = (b.vx - a.vx) * nx + (b.vy - a.vy) * ny
          if (relVDotN > COLLISION_THRESHOLD) {
            const cx = (a.x + b.x) * 0.5
            const cy = (a.y + b.y) * 0.5
            this.spawnCollisionEffect(cx, cy)
          }
        }

        resolveCircleCircle(a, b)
      }
    }
  }

  private eliminateOutside(): void {
    const boundary = this.state.boundaryRadius
    for (let i = 0; i < TOTAL; i++) {
      const c = this.pool[i]!
      if (!c.alive) continue
      const d = Math.sqrt(c.x * c.x + c.y * c.y)
      if (d > boundary - c.radius) {
        c.alive = false
        this.spawnEffect(c.x, c.y, c.team)
        this.state.eliminationCount++
      }
    }
  }

  // ─── LAST_COLOR_STANDING winner logic ────────────────────────────────────

  private findWinner(): TeamId | null {
    if (this.currentRecipeId === 'LAST_COLOR_STANDING') {
      return this.findLastColorStandingWinner()
    }
    // Default: last individual standing
    let found: TeamId | null = null
    for (let i = 0; i < TOTAL; i++) {
      if (!this.pool[i]!.alive) continue
      const t = this.pool[i]!.team
      if (found === null) { found = t }
      else if (found !== t) return null
    }
    return found
  }

  private findLastColorStandingWinner(): TeamId | null {
    // A team is "alive" if any of its members is alive
    const teamsAlive = new Set<TeamId>()
    for (let i = 0; i < TOTAL; i++) {
      if (this.pool[i]!.alive) teamsAlive.add(this.pool[i]!.team)
    }
    if (teamsAlive.size === 1) {
      return [...teamsAlive][0]!
    }
    return null
  }

  // ─── Team elimination checking ────────────────────────────────────────────

  private checkTeamEliminations(): void {
    // Track teams that just became fully eliminated this tick
    for (const team of TEAMS) {
      const row = this.state.scoreboardRows.find(r => r.team === team)
      if (!row || row.isEliminated) continue

      let alive = 0
      for (let i = 0; i < TOTAL; i++) {
        if (this.pool[i]!.team === team && this.pool[i]!.alive) alive++
      }
      row.aliveCount = alive

      if (alive === 0) {
        row.isEliminated = true
        // Track finish order
        if (!this.finishOrderInProgress.includes(team)) {
          // Insert at front of "lost teams" (we'll reverse at end)
          this.finishOrderInProgress.unshift(team)
        }
        // Show team eliminated announcement
        this.state.teamEliminatedLabel = `${team} ELIMINATED`
        this.state.teamEliminatedTicksRemaining = TEAM_ELIM_DURATION
      }
    }

    // Also update alive counts for living teams
    for (const row of this.state.scoreboardRows) {
      if (row.isEliminated) continue
      let alive = 0
      for (let i = 0; i < TOTAL; i++) {
        if (this.pool[i]!.team === row.team && this.pool[i]!.alive) alive++
      }
      row.aliveCount = alive
    }

    // Check for "FINAL TWO TEAMS"
    const teamsAlive = new Set<TeamId>()
    for (let i = 0; i < TOTAL; i++) {
      if (this.pool[i]!.alive) teamsAlive.add(this.pool[i]!.team)
    }
    if (teamsAlive.size === 2 && !this.state.shownFinalTwo) {
      this.state.shownFinalTwo = true
      this.state.milestoneLabel = 'FINAL TWO TEAMS'
      this.state.milestoneTicksRemaining = MILESTONE_DURATION
    }
  }

  // ─── Milestone checking ───────────────────────────────────────────────────

  private checkMilestones(): void {
    let alive = 0
    for (let i = 0; i < TOTAL; i++) {
      if (this.pool[i]!.alive) alive++
    }

    if (!this.state.shownFinal10 && alive <= 10) {
      this.state.shownFinal10 = true
      this.state.milestoneLabel = 'FINAL 10'
      this.state.milestoneTicksRemaining = MILESTONE_DURATION
    }
    if (!this.state.shownFinal5 && alive <= 5) {
      this.state.shownFinal5 = true
      this.state.milestoneLabel = 'FINAL 5'
      this.state.milestoneTicksRemaining = MILESTONE_DURATION
    }
  }

  private triggerWinner(team: TeamId): void {
    this.state.phase = 'WINNER'
    this.state.winnerTeam = team
    this.state.phaseTicksRemaining = this.t(T.WINNER_T, T.WINNER_N)
    this.endEvent()

    // Compute stats
    this.state.roundDurationSec = Math.floor(this.state.roundTick / 60)
    let survivors = 0
    for (let i = 0; i < TOTAL; i++) if (this.pool[i]!.alive) survivors++
    this.state.survivorCount    = survivors
    this.state.eliminationCount = TOTAL - survivors

    // Complete the finish order: winner is first, then already-eliminated teams reverse
    // finishOrderInProgress was built front-to-back as teams eliminated (last = most recent)
    // So finishOrderInProgress[0] = first team to die, last = most recent before winner
    // We need: [winner, last eliminated, ..., first eliminated]
    const finishOrder: TeamId[] = [team]
    // Remaining eliminated teams (not the winner) in reverse order of elimination
    // (finishOrderInProgress is ordered first-to-die at front)
    for (let k = this.finishOrderInProgress.length - 1; k >= 0; k--) {
      const t2 = this.finishOrderInProgress[k]!
      if (t2 !== team) finishOrder.push(t2)
    }
    // Add any teams that didn't die (shouldn't happen normally but safety)
    for (const t2 of TEAMS) {
      if (!finishOrder.includes(t2)) finishOrder.push(t2)
    }
    this.finishOrderInProgress = finishOrder
    this.state.roundFinishOrder = finishOrder

    // Championship win display
    if (this.isChampionship) {
      this.state.championshipWin.active = true
      this.state.championshipWin.team = team
      // Points = 1st place base × multiplier
      this.state.championshipWin.pointsGained = Math.round(6 * this.pointMultiplier)
    }
  }

  private majorityTeam(): TeamId {
    const counts = new Array<number>(TEAMS.length).fill(0)
    for (let i = 0; i < TOTAL; i++) {
      if (this.pool[i]!.alive) {
        const ti = TEAMS.indexOf(this.pool[i]!.team)
        if (ti >= 0) counts[ti]!++
      }
    }
    let best = 0
    for (let k = 1; k < TEAMS.length; k++) {
      if (counts[k]! > counts[best]!) best = k
    }
    return TEAMS[best]!
  }

  private ageEffects(): void {
    for (let i = 0; i < this.effectPool.length; i++) {
      const e = this.effectPool[i]!
      if (!e.active) continue
      e.age++
      if (e.age >= e.maxAge) e.active = false
    }
    for (let i = 0; i < this.pulsePool.length; i++) {
      const p = this.pulsePool[i]!
      if (!p.active) continue
      p.age++
      if (p.age >= p.maxAge) p.active = false
    }
    for (let i = 0; i < this.collisionPool.length; i++) {
      const e = this.collisionPool[i]!
      if (!e.active) continue
      e.age++
      if (e.age >= e.maxAge) e.active = false
    }
    // Leaderboard tick
    if (this.state.leaderboard.active && this.state.leaderboard.ticksRemaining > 0) {
      // ticked in main step() LEADERBOARD branch
    }
    // Intro tick
    if (this.state.roundIntro.active && this.state.roundIntro.ticksRemaining > 0) {
      this.state.roundIntro.ticksRemaining--
    }
  }
}

// ─── Utility ──────────────────────────────────────────────────────────────────

function angleDiff(a: number, b: number): number {
  let d = a - b
  while (d >  Math.PI) d -= Math.PI * 2
  while (d < -Math.PI) d += Math.PI * 2
  return d
}
